### ISSUE TITLE
Connecting to Influxdb Telegraf

### ISSUE THREAD

**Issue by Sineos** [ioBroker/ioBroker.influxdb#78] opened 2021-01-12 19:15 UTC
[Telegraf](https://docs.influxdata.com/telegraf/v1.17/) is kind of a proxy / agent between InfluxDB and potential data sources.
As Telegraf "speaks" InfluxDB v1.x, I had hoped that ioBroker.influxdb is able to connect to it. Unfortunately, I cannot get it to work.

telegraf.conf:
```
[[inputs.influxdb_listener]]
  service_address = "192.168.178.8:8186"
  read_timeout = "10s"
  write_timeout = "10s"
  max_body_size = 0
```

ioBroker.influxdb debug log:
```
influxdb.1 | 2021-01-12 20:07:26.157 | error | (26614) Error: bad response from server
influxdb.1 | 2021-01-12 20:07:26.143 | info | (26614) Connecting http://192.168.178.8:8186 ...
influxdb.1 | 2021-01-12 20:07:16.141 | error | (26614) Error: bad response from server
influxdb.1 | 2021-01-12 20:07:16.127 | info | (26614) Connecting http://192.168.178.8:8186 ...
influxdb.1 | 2021-01-12 20:07:06.127 | error | (26614) Error: bad response from server
influxdb.1 | 2021-01-12 20:07:06.119 | debug | (26614) connected set to false
influxdb.1 | 2021-01-12 20:07:06.091 | info | (26614) Connecting http://192.168.178.8:8186 ...
influxdb.1 | 2021-01-12 20:07:06.090 | info | (26614) No stored data from last exit found
influxdb.1 | 2021-01-12 20:07:06.069 | info | (26614) starting. Version 1.9.3 in /opt/iobroker/node_modules/iobroker.influxdb, node: v10.22.0, js-controller: 3.1.6
```

Am I missing something?

**Comment by Apollon77** [comment] 2021-01-13 21:47
Good idea with Telegraf speking Influxdb 1 ... whats the real response? I need to check it the next days too

**Comment by Sineos** [comment] 2021-01-13 22:49
The adapter log, even when set to "silly" does not containing anything useful

```
influxdb.1 | 2021-01-13 23:48:19.013 | info | (27916) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
influxdb.1 | 2021-01-13 23:48:19.012 | debug | (27916) Plugin sentry destroyed
influxdb.1 | 2021-01-13 23:48:18.809 | debug | (27916) sendTo "stopInstance" to system.adapter.system.host.smarthub from system.adapter.influxdb.1: stopped
influxdb.1 | 2021-01-13 23:48:18.807 | silly | (27916) States system redis pmessage  messagebox.system.adapter.influxdb.1/messagebox.system.adapter.influxdb.1:{"command":"stopInstance","message":null,"from":"system.host.smarthub","callback":{"mess
influxdb.1 | 2021-01-13 23:48:18.803 | silly | (27916) Objects user redis pmessage  */cfg.o.system.adapter.influxdb.1:{"_id":"system.adapter.influxdb.1","type":"instance","common":{"name":"influxdb","desc":{"en":"Logging  of states into InfluxDB","
host.smarthub | 2021-01-13 23:48:18.803 | info | stopInstance system.adapter.influxdb.1 (force=false, process=true)
host.smarthub | 2021-01-13 23:48:18.802 | info | "system.adapter.influxdb.1" disabled
influxdb.1 | 2021-01-13 23:48:09.221 | error | (27916) Error: bad response from server
influxdb.1 | 2021-01-13 23:48:09.207 | info | (27916) Connecting http://192.168.178.8:8186 ...
influxdb.1 | 2021-01-13 23:47:59.207 | error | (27916) Error: bad response from server
influxdb.1 | 2021-01-13 23:47:59.195 | info | (27916) Connecting http://192.168.178.8:8186 ...
influxdb.1 | 2021-01-13 23:47:52.979 | debug | (27916) system.adapter.admin.0: logging true
influxdb.1 | 2021-01-13 23:47:52.978 | silly | (27916) States system redis pmessage  io.*.logging/io.system.adapter.admin.0.logging:{"val":true,"ack":true,"ts":1610578072976,"q":0,"from":"system.adapter.admin.0","lc":1610578072976}
influxdb.1 | 2021-01-13 23:47:49.193 | error | (27916) Error: bad response from server
influxdb.1 | 2021-01-13 23:47:49.143 | silly | (27916) States system redis pmessage  io.system.adapter.influxdb.1.logLevel/io.system.adapter.influxdb.1.logLevel:{"val":"silly","ack":true,"ts":1610578069131,"q":0,"from":"system.adapter.influxdb.1",
influxdb.1 | 2021-01-13 23:47:49.141 | debug | (27916) connected set to false
influxdb.1 | 2021-01-13 23:47:49.113 | info | (27916) Connecting http://192.168.178.8:8186 ...
influxdb.1 | 2021-01-13 23:47:49.113 | silly | (27916) redis psubscribe cfg.o.*
influxdb.1 | 2021-01-13 23:47:49.112 | info | (27916) No stored data from last exit found
influxdb.1 | 2021-01-13 23:47:49.091 | info | (27916) starting. Version 1.9.3 in /opt/iobroker/node_modules/iobroker.influxdb, node: v10.22.0, js-controller: 3.1.6
influxdb.1 | 2021-01-13 23:47:49.011 | debug | (27916) Plugin sentry Initialize Plugin (enabled=true)
influxdb.1 | 2021-01-13 23:47:48.398 | debug | (27916) statesDB connected
influxdb.1 | 2021-01-13 23:47:48.398 | debug | (27916) States connected to redis: 127.0.0.1:6379
influxdb.1 | 2021-01-13 23:47:48.395 | debug | (27916) States create System PubSub Client
influxdb.1 | 2021-01-13 23:47:48.393 | debug | (27916) States create User PubSub Client
influxdb.1 | 2021-01-13 23:47:48.390 | debug | (27916) Redis States: Use Redis connection: 127.0.0.1:6379
influxdb.1 | 2021-01-13 23:47:48.389 | debug | (27916) objectDB connected
influxdb.1 | 2021-01-13 23:47:48.384 | debug | (27916) Objects connected to redis: 127.0.0.1:9001
influxdb.1 | 2021-01-13 23:47:48.379 | debug | (27916) Objects client initialize lua scripts
influxdb.1 | 2021-01-13 23:47:48.379 | debug | (27916) Objects create User PubSub Client
influxdb.1 | 2021-01-13 23:47:48.378 | debug | (27916) Objects create System PubSub Client
influxdb.1 | 2021-01-13 23:47:48.376 | debug | (27916) Objects client ready ... initialize now
influxdb.1 | 2021-01-13 23:47:48.357 | debug | (27916) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.smarthub | 2021-01-13 23:47:47.751 | info | instance system.adapter.influxdb.1 started with pid 27916
host.smarthub | 2021-01-13 23:47:47.725 | info | "system.adapter.influxdb.1" enabled
```

**Comment by Apollon77** [comment] 2021-01-13 22:56
it might be the same issue as with the influxdb 1 compat mode in influxdb 2 that "show databases" is not supported and thats why this query fails

**Comment by Sineos** [comment] 2021-01-13 23:00
Looks like nothing is ever received on the telegraf side. Log from telegraf set to debug:

```
2021-01-13T22:58:05Z I! Loaded inputs: influxdb_listener
2021-01-13T22:58:05Z I! Loaded aggregators:
2021-01-13T22:58:05Z I! Loaded processors:
2021-01-13T22:58:05Z I! Loaded outputs: influxdb_v2
2021-01-13T22:58:05Z I! Tags enabled: host=dc01
2021-01-13T22:58:05Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"dc01", Flush Interval:10s
2021-01-13T22:58:05Z D! [agent] Initializing plugins
2021-01-13T22:58:05Z D! [agent] Connecting outputs
2021-01-13T22:58:05Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2021-01-13T22:58:05Z D! [agent] Successfully connected to outputs.influxdb_v2
2021-01-13T22:58:05Z D! [agent] Starting service inputs
2021-01-13T22:58:05Z I! [inputs.influxdb_listener] Started HTTP listener service on 192.168.178.8:8186
2021-01-13T22:58:15Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2021-01-13T22:58:25Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2021-01-13T22:58:35Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```

**Comment by Apollon77** [comment] 2021-01-14 07:09
depends on what they log there, or?! ;-)

maybe try to use a influxdb 1 client to connect yourself and see what is returned on "show databases" ... I checke dthe code of the used indluxdb library and that "bad response" error comes if "show databases" is not answering as expected and we know that the influxdb 2 integrated influxdb 1 compat layer is having the same issue

**Comment by Sineos** [comment] 2021-01-15 09:11
*sigh*, I had hoped that this would be an easy and future safe way to connect.

Would you consider implementing a "stupid" json based line protocol on the to simply dump data into influxdb? I think this would make the adapter a lot less complex.

If my observations are correct, then the adapter fails on the query for the databases, i.e. the `show databases` command. Strictly speaking it should not be necessary, even more so when using tools like Telegraf.

IMHO the only true functionality that is needed is to send out data. All influxdb management tasks, like creating / deleting etc. can be achieved via multiple other ways (CLI, Grafana, Kapacitor etc.)

**Comment by Apollon77** [comment] 2021-01-15 12:22
In fact it is basically as discussed in #45 all known "influxdb 1 compat lavels" do not support the database management layer. this means that creating the needed table structure or databases are not possible at all.

So one option is to rewrite the adapter completly to work with influxdb 2.

An alternative would be to assume influxdb 2.0 as soon as "show databases" is not working and check  somehow different if it is created and somehow log the needed "create database/tables" commands for the user to create them manually.

We need to find time to look into this

**Comment by Sineos** [comment] 2021-01-15 15:57
I think omitting the DB management layer and using the  [InfluxDB HTTP API](https://docs.influxdata.com/influxdb/v1.8/guides/write_data/) would provide compatibility to InfluxDB v1.x and v2.x and to Telegraf.

E.g. Telegraf can consume [HTTP requests](https://github.com/influxdata/telegraf/blob/release-1.17/plugins/inputs/influxdb_listener/README.md) like

**InfluxDB v1.x and Telegraf**
```
curl -i -XPOST 'http://localhost:8086/write?db=mydb' \
--data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000''
```

**InfluxDB v2.x**
```
curl -i -XPOST 'http://localhost:8086/api/v2/write?bucket=db/rp&precision=ns' \
--header 'Authorization: Token username:password' \
--data-raw 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'
```

which does in fact include all relevant params needed to store ioBroker's data:
- The DB (ok, the user would have to create it himself, but IMO minor)
- Tag Keys and Tag Value
- Field Keys and Field Value
- Timestamp

There is even a meaning HTTP response when writing to a not existing DB: https://docs.influxdata.com/influxdb/v1.8/guides/write_data/#writing-a-point-to-a-database-that-doesn-t-exist

**Comment by Apollon77** [comment] 2021-01-15 17:19
The adapter uses an node linrary for all communication with influxdb currently and so starting http stuff aside will not make it better

**Comment by ThetaGamma** [comment] 2021-01-31 20:23
Perhaps my investigations/thoughs help getting towards a solution to this problem. 

in influxdb v2 there are no more "databases" and "retention policies", they are both integrated in "buckets". To use retention policies, they use a compatibility layer called "DBRP mapping service"

The steps I recognize in `function connect(adapter)` is (1) get the names of the databases, (2) create a new database if not existing and (3) change the retention policy.

The corresponding tasks could be done with the [official javascript lib](https://github.com/influxdata/influxdb-client-js), Refering to [the example](https://github.com/influxdata/influxdb-client-js/blob/master/examples/createBucket.js) we can archive (1) by using `bucketsAPI.getBuckets` (2) by using `bucketsAPI.postBuckets` (3) Use the [DBPR mapping API](https://docs.influxdata.com/influxdb/v2.0/api/#operation/PatchDBRPID)

Let's assume we can toggle between v1 and v2 in the admin interface, then we can choose within function connect(adapter) which client library to use.

**Comment by Sineos** [comment] 2021-01-31 21:05
Well, the solution to use the official v2 library and rewrite the entire adapter was quite obvious from the beginning...now the challenge remains to find someone who is a) capable of doing it, b) willing to do it and c) has the time to do it

**Comment by Apollon77** [comment] 2021-01-31 21:48
And if this is really it ... it IS a duplicate of #45

**Closed by Apollon77** 2021-01-31 21:48 UTC

**Comment by Sineos** [comment] 2021-02-01 06:24
Basically yes, since this idea fails at exactly the same spot as the compatibility layer approach.

**Comment by Apollon77** [comment] 2021-02-01 06:37
it is in fact an 50% rewrite of the adapter ...

**Comment by Sineos** [comment] 2021-02-01 07:20
> it is in fact an 50% rewrite of the adapter ...

I can imagine this and on top it is a real complex one (unfortunately way over my coding payroll).

Still, InfluxDB for me is one of the most important elements in my ioBroker install and I sincerely hope that soon we can take it to the 2.x level. 
Keep up the great work with ioBroker!
