### ISSUE TITLE
Error message: "404 page not found" with node.js 20

### ISSUE THREAD

**Issue by OhlH** [ioBroker/ioBroker.influxdb#342] opened 2023-06-24 16:42 UTC
# Error description
Since the last update I initiated influxdb is unable to save data to influxdb. Error: 404 page not found. Reconfiguring and testing "Verbindung testen" results always in the same error 404.

## Narrowing it down
I tried out everything:
- I re-typed the password
- I backuped influxdb, purged it, reinstalled it, created new users - but the result is the same: grafana works, iobroker throws error 404.
## Does influx work correctly?
I assume **it does**, because
- Grafana can read the historical data from before the update
- Grafana can use iobroker's credentials
- Grafana's "Save&Test" returns success
- `curl -sL -I localhost:8086` returns

> HTTP/1.1 404 Not Found
> Content-Type: text/plain; charset=utf-8
> X-Content-Type-Options: nosniff
> X-Influxdb-Build: OSS
> X-Influxdb-Version: 1.8.10
> Date: Sat, 24 Jun 2023 16:24:03 GMT

- `curl -sL -I localhost:8086/ping` returns

> HTTP/1.1 204 No Content
> Content-Type: application/json
> Request-Id: 5df*****-12ab-11ee-8023-*********
> X-Influxdb-Build: OSS
> X-Influxdb-Version: 1.8.10
> X-Request-Id: 5df*****-12ab-11ee-8023-*********

- `curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=iobroker" --data-urlencode "q=SELECT mean(\"value\") FROM \"measurement\" WHERE *"`
returns - as expected - an error message, because of the invalid condition expression - but not 404!

> {
>     "results": [
>         {
>             "statement_id": 0,
>             "error": "invalid condition expression: *"
>         }
>     ]
> }

# To Reproduce
It is inevitable to _not_ reproduce the error. I do not know _how_ to reproduce it.

# Expected behavior  
adapter writes data to influxdb

# Versions
 - Adapter version: influxdb v3.2.0
 - JS-Controller version: v4.0.24
 - Node version: v20.2.0
 - Operating system: Raspbian GNU/Linux 11 (bullseye)
 - influxdb: v1.8.10

**Comment by OhlH** [comment] 2023-06-24 17:27
Well I found a solution myself, and maybe the error: "Node version: v20.2.0". A downgrade to 18.16.0 helped. Developers might keep this in mind.

**Comment by Apollon77** [comment] 2023-07-09 13:21
is it possible for you to provide a debug log?

**Comment by Apollon77** [comment] 2023-07-09 15:26
@OhlH Are you sure on OS? could it be bookworm?

**Comment by winnyschuster** [comment] 2023-07-22 21:30
> Well I found a solution myself, and maybe the error: "Node version: v20.2.0". A downgrade to 18.16.0 helped. Developers might keep this in mind: the future waits with problems to solve.

there's a good chance that disabling Sentry solves the problem with node20. In Instances click the green triangle to the right and see if that helps. Though you have downgraded to node18, its highly appreciated if you could test again with node20 :-)

**Comment by Apollon77** [comment] 2023-07-25 08:51
related https://github.com/getsentry/sentry-javascript/issues/8552

**Comment by ecunplugged** [comment] 2023-08-29 21:53
> > Well I found a solution myself, and maybe the error: "Node version: v20.2.0". A downgrade to 18.16.0 helped. Developers might keep this in mind: the future waits with problems to solve.
> 
> there's a good chance that disabling Sentry solves the problem with node20. In Instances click the green triangle to the right and see if that helps. Though you have downgraded to node18, its highly appreciated if you could test again with node20 :-)

correct! I did the upgrade to node20 and had the same issue. Disabling Sentry does the trick for me. Merci.

**Comment by Apollon77** [comment] 2023-08-29 22:34
which nodejs 20 you use? The very latest should have that fixed

**Comment by winnyschuster** [comment] 2023-08-29 22:45
> which nodejs 20 you use? The very latest should have that fixed

not yet, 20.6.0 will have that fix but the release was postponed several times. Last news is that it will be released today but i doubt that because there are still failing tests actually

**Comment by winnyschuster** [comment] 2023-09-04 22:38
> correct! I did the upgrade to node20 and had the same issue. Disabling Sentry does the trick for me. Merci.

could you please retry with node 20.6.0 enabling sentry?

**Comment by ecunplugged** [comment] 2023-09-05 14:42
> > correct! I did the upgrade to node20 and had the same issue. Disabling Sentry does the trick for me. Merci.
> 
> could you please retry with node 20.6.0 and enabling sentry?

Yes, confirmed. Upgraded to 20.6 and re-enabled Sentry w/o any problems. For me this case is closed. Thank you for your support.

**Closed** 2023-09-06 15:22 UTC
