### ISSUE TITLE
Measurements comming from origin adapter and influxdb adapter

### ISSUE THREAD

**Issue by peterbaumert** [ioBroker/ioBroker.influxdb#299] opened 2022-10-10 17:21 UTC
**Describe the bug**  
For every measurement I get the measurement one time from the originating adapter and one time from influxdb adapter even with different values but same timestamp.

**To Reproduce**  
1. Go to any object and enable influxdb
2. browse Influx data
3. See error

**Expected behavior**  
I would expect to only get the measurement from the originating adapter.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/1212934/194920702-6cbbca36-89cd-4236-870e-d2f784195a48.png)

**Versions:**  
 - Adapter version: 3.2.0
 - JS-Controller version: 4.0.23
 - Node version: v14.20.0
 - Operating system: Debian 11

**Comment by Apollon77** [comment] 2022-10-11 09:28
If influxdb loggs values then these are the "relog because unchanged values" ... or values logged because of the "optimization for charting" (that can be turned off in conbfig). Please see readme. and the timestamp will be different ... Please enable debug log of the instance and enable enhanced debug for an affected datapoint and the log will show you exactly what happens.

For more details please post debug log and tell what is wrong.

**Comment by Marc-Berg** [comment] 2024-01-06 17:05
I would suggest closing this issue. The cause has been explained, no further response.

**Closed** 2024-01-07 14:59 UTC
Labels: question
