### ISSUE TITLE
API changed with influ 2.0

### ISSUE THREAD

**Issue by EdgarM73** [ioBroker/ioBroker.influxdb#74] opened 2020-11-12 17:22 UTC
Hi there,

with the current Version 2.0 of influxdb the API has changed and this adapter will no longer be able to connect to the db.

regards
E

**Comment by EdgarM73** [comment] 2020-11-12 18:00
once installed, there is a information how to connect via node.js:

initialize:
`const {InfluxDB} = require('@influxdata/influxdb-client')

// You can generate a Token from the "Tokens Tab" in the UI
const token = '2-R0tZAcmk13vPcjmhEyTjwo3Gq5sASAytaEsJQrJlVQpf7--99Npwgyfq99-7GE3V3QgSJJyiORUmg-iWKzUg=='
const org = 'iobroker'
const bucket = 'iobroker'

const client = new InfluxDB({url: 'http://172.23.2.6:8086', token: token})`

write:
`const {Point} = require('@influxdata/influxdb-client')
const writeApi = client.getWriteApi(org, bucket)
writeApi.useDefaultTags({host: 'host1'})

const point = new Point('mem')
  .floatField('used_percent', 23.43234543)
writeApi.writePoint(point)
writeApi
    .close()
    .then(() => {
        console.log('FINISHED')
    })
    .catch(e => {
        console.error(e)
        console.log('\\nFinished ERROR')
    })`

query:

`const queryApi = client.getQueryApi(org)

const query = \`from(bucket: \"\${bucket}\") |> range(start: -1h)\`
queryApi.queryRows(query, {
  next(row, tableMeta) {
    const o = tableMeta.toObject(row)
    console.log(
      \`\${o._time} \${o._measurement} in \'\${o.location}\' (\${o.example}): \${o._field}=\${o._value}\`
    )
  },
  error(error) {
    console.error(error)
    console.log('\\nFinished ERROR')
  },
  complete() {
    console.log('\\nFinished SUCCESS')
  },
})`

**Comment by Apollon77** [comment] 2020-11-12 20:49
duplicate of #45 basically.

In fact there is a v1 fallback API also in influxdb 2, but some commands are not available via that. I also have an issue open with influxdb  repo to find a way to detect the db version and then we can see how we do things

**Comment by Apollon77** [comment] 2020-11-12 20:50
And for your code: Yes but switching to the other library is a big rewrite of the adapter. We need to see how we do that and find time for this, so maybe the v1 compatibility layer is the first approach

**Closed by Apollon77** 2020-11-12 20:50 UTC
