### ISSUE TITLE
use additional CA file for certificate verification

### ISSUE THREAD

**Issue by andreklug** [ioBroker/ioBroker.influxdb#205] opened 2022-01-26 09:10 UTC
I am trying to connect the recent 2.40 release to my self hosted InfluxDB server. I am using my own CA to verify certificates. My ioBroker runs in LXC, not in docker.

The CA certificate file is stored at /etc/ssl/homelab.local_CA.crt

After reading in other issues, I updated /opt/iobroker/node_modules/influx/lib/InfluxRequest.js to this

```
var request = require('request')
var _ = require('lodash')
var url = require('url')
const fs = require('fs'); ### ADDED

var resubmitErrorCodes = ['ETIMEDOUT', 'ESOCKETTIMEDOUT', 'ECONNRESET', 'ECONNREFUSED', 'EHOSTUNREACH']

function InfluxRequest (options) {
  if (!options) options = {}
  this.index = 0
  this.hostsAvailable = []
  this.hostsDisabled = []
  this.defaultRequestOptions = {
    timeout: null
    ca: fs.readFile('/etc/ssl/homelab.local_CA.crt')  ### ADDED
  }
  this.setRequestTimeout(options.requestTimeout)
  this.options = {
    failoverTimeout: options.failoverTimeout || 60000,
    maxRetries: options.maxRetries || 2
  }
}
```

This doesn't work, maybe I got the code wrong, but I am unable to find working examples (error log added below). I followed an example at https://nodejs.dev/learn/reading-files-with-nodejs

Ideally it would be possible to specify an alternative CA in the UI, but for me it would be also okay to read the CA from the js code if that's not feasible.

Thanks in advance for your help!

Error log from ioBroker:

```
host.iobroker | 2022-01-26 10:11:39.799 | error | instance system.adapter.influxdb.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2022-01-26 10:11:39.799 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.iobroker | 2022-01-26 10:11:39.799 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)
host.iobroker | 2022-01-26 10:11:39.799 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/influx/index.js:1:21)
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:887:19)
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:963:27)
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: at wrapSafe (internal/modules/cjs/loader.js:915:16)
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: SyntaxError: Unexpected identifier
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: ^^
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: ca: fs.readFile('/etc/ssl/homelab.local_CA.crt')
host.iobroker | 2022-01-26 10:11:39.798 | error | Caught by controller[0]: /opt/iobroker/node_modules/influx/lib/InfluxRequest.js:15
```

**Comment by Apollon77** [comment] 2022-01-26 09:18
Firstof all this is a duplicate of #69 
And you issue is exactly writen in the error message ... Syntact erro ... you should add a "," at the end of the " timeout: null" line

**Closed by Apollon77** 2022-01-26 09:18 UTC

**Comment by Apollon77** [comment] 2022-01-26 09:20
PS: Honestly I also do not understand why you change the 2 library used for an 1.x InfluxDB integration?!?!? Influxdb 2.x support is only in in the newest 2.x version of the adapter

**Comment by andreklug** [comment] 2022-01-26 09:36
I don't understand your last message, I am using v2.4.0 set to DB-Version 2.x:

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/13343357/151138829-ee686a9f-9e6a-45be-bada-04f9c7e53ae1.png">


<img width="1529" alt="image" src="https://user-images.githubusercontent.com/13343357/151138770-afd2f071-1268-40f0-8ef2-1fe77cadc6cf.png">

**Comment by andreklug** [comment] 2022-01-26 09:41
Thanks for pointing out the syntax error (I struggle to learn coding). The error message is gone and back to this: 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/13343357/151139629-d8b08d42-92dd-4e22-b8e1-9d52b2f5882e.png">

Is there anything else I am missing?

**Comment by Apollon77** [comment] 2022-01-26 10:14
> , I am using v2.4.0 set to DB-Version 2.x:

Ok, but honestly then the code place where you did your change is simply not used because the "Infliux" library is only used for 1.2 communication ... for 2.x the code in node_modules/@influxdata/influxdb-client* is used. So you change simply has no effect if you chose influxdb 2.x :-)
